name: Rust Release

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        run: cargo build --release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "target/release/dtf"
          generate_release_notes: true
#      - uses: mislav/bump-homebrew-formula-action@v3
#        if: ${{ !contains(github.ref, '-') }} # skip prereleases
#        with:
#          formula-name: my_formula
#          formula-path: Formula/m/my_formula.rb
#          homebrew-tap: Homebrew/homebrew-core
#          base-branch: master
#          download-url: https://example.com/foo/${{ steps.extract-version.outputs.tag-name }}.tar.gz
#          commit-message: |
#            {{formulaName}} {{version}}
#
#            Created by https://github.com/mislav/bump-homebrew-formula-action
#        env:
#          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
#          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}